#!/bin/bash
clear
echo "Welcome to openSUSE Setup"
echo " "
echo " "
echo Please choose a pasaword for user root 
passwd
echo " "
echo " "
echo Create New User 
echo "Username: " 
read uservar
echo "Full Name: " 
read fullnamevar
echo " "
echo Adding user $uservar
useradd -m $uservar -c "$fullnamevar"
echo " "
echo Please choose a pasaword for user $uservar
passwd $uservar
echo " "
echo " "
echo "Patching Chromium"
wget -q https://raw.githubusercontent.com/radumamy/Termux-openSUSE/master/Scripts/Patches/chromium-patch -O /usr/local/bin/chromium-patch 
chmod +x /usr/local/bin/chromium-patch
chromium-patch
echo " "
echo " "
wget -q https://raw.githubusercontent.com/radumamy/Termux-openSUSE/master/Scripts/Patches/yast-patch -O /usr/local/bin/yast-patch 
chmod +x /usr/local/bin/yast-patch
echo " "
echo "Setting up VNC" 
wget - q https://raw.githubusercontent.com/radumamy/Termux-openSUSE/master/Scripts/Installer/openSUSE/vnc-server.sh -O ~/vnc-server.sh 
bash ~/vnc-server.sh 
sed -i '1d' ~/.bash_profile
echo "exec su - $uservar" >> /usr/local/bin/switch-user
chmod +x /usr/local/bin/switch-user
