#!/bin/bash
rm -f /usr/share/applications/chromium-browser.desktop
echo "[Desktop Entry]
Version=1.0
Name=Chromium
Comment=Browse the World Wide Web
GenericName=Web Browser
Exec=chromium --no-sandbox %u
Terminal=false
X-MultipleArgs=false
Type=Application
Icon=chromium-browser
Categories=Network;WebBrowser;
MimeType=text/html;text/xml;application/xhtml+xml;x-scheme-handler/http;x-scheme-handler/https;
StartupWMClass=Chromium

X-Desktop-File-Install-Version=0.26" > /usr/share/applications/chromium-browser.desktop
